package org.gy.framework.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WeixinMenuConfig;
import org.gy.framework.model.WeixinMenuConfigExample;

public interface WeixinMenuConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int countByExample(WeixinMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int insert(WeixinMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int insertSelective(WeixinMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    List<WeixinMenuConfig> selectByExample(WeixinMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    WeixinMenuConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinMenuConfig record, @Param("example") WeixinMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinMenuConfig record, @Param("example") WeixinMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinMenuConfig record);
}