package org.gy.framework.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WeixinReplyLog;
import org.gy.framework.model.WeixinReplyLogExample;

public interface WeixinReplyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int countByExample(WeixinReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int insert(WeixinReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int insertSelective(WeixinReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    List<WeixinReplyLog> selectByExample(WeixinReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    WeixinReplyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinReplyLog record, @Param("example") WeixinReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinReplyLog record, @Param("example") WeixinReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_reply_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinReplyLog record);
}