package org.gy.framework.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WeixinUserRecord;
import org.gy.framework.model.WeixinUserRecordExample;

public interface WeixinUserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int countByExample(WeixinUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int insert(WeixinUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int insertSelective(WeixinUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    List<WeixinUserRecord> selectByExample(WeixinUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    WeixinUserRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinUserRecord record, @Param("example") WeixinUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinUserRecord record, @Param("example") WeixinUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinUserRecord record);
}