package org.gy.framework.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WxAppConfig;
import org.gy.framework.model.WxAppConfigExample;

public interface WxAppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int countByExample(WxAppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int deleteByExample(WxAppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int insert(WxAppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int insertSelective(WxAppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    List<WxAppConfig> selectByExample(WxAppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    WxAppConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxAppConfig record, @Param("example") WxAppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxAppConfig record, @Param("example") WxAppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxAppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_app_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxAppConfig record);
}