package org.gy.framework.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WxMenuConfig;
import org.gy.framework.model.WxMenuConfigExample;

public interface WxMenuConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int countByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int deleteByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int insert(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int insertSelective(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    List<WxMenuConfig> selectByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    WxMenuConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxMenuConfig record, @Param("example") WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxMenuConfig record, @Param("example") WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxMenuConfig record);
}