package org.gy.framework.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WxReplyLog;
import org.gy.framework.model.WxReplyLogExample;

public interface WxReplyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int countByExample(WxReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int deleteByExample(WxReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int insert(WxReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int insertSelective(WxReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    List<WxReplyLog> selectByExample(WxReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    WxReplyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxReplyLog record, @Param("example") WxReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxReplyLog record, @Param("example") WxReplyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxReplyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_reply_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxReplyLog record);
}