package org.gy.framework.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.gy.framework.model.WxUserRecord;
import org.gy.framework.model.WxUserRecordExample;

public interface WxUserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int countByExample(WxUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int deleteByExample(WxUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int insert(WxUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int insertSelective(WxUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    List<WxUserRecord> selectByExample(WxUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    WxUserRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxUserRecord record, @Param("example") WxUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxUserRecord record, @Param("example") WxUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxUserRecord record);
}